jQuery(document).ready(function(){
	$('#slider-carousel').carouFredSel({
         width:'100%',
         responsive:true,
         circular:true,
         scroll:{
                 items:1,
                 duration:500,
                 pauseOnHover:true  
         },
         auto:true,
         items:
         {
             visible:{
                   min:1,
                   max:1
             },
             height:"variable"
         },
         pagination:{
             container:".sliderpager",
             pageAnchorBuilder:false
         }
     });
    $(window).scroll(function(){
        let top=$(window).scrollTop();
        if(top>=60){
            $("header").addClass("nav-active");
        }else{
            if($("header").hasClass("nav-active")){
                $("header").removeClass("nav-active");
            }
        }
    })
});